server:
  port: 8080
  servlet:
    context-path: ''
  tomcat:
    max-threads: 20
  compression:
    enabled: true

spring:
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: false
  datasource:
    # 初始化数据导入
    data: classpath*:db/data.sql
    initialization-mode: always
    continue-on-error: true

    # h2 内存数据库 配置
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/.zfile/db/zfile
    username: zfile
    password: 123456

    # MySQL 配置
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
#    username: root
#    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  resources:
    chain:
      gzipped: true
  profiles:
    active: dev
zfile:
  cache:
    timeout: 300
  constant:
    header: header.md
    password: password.txt
  onedirve:
    clientId: 09939809-c617-43c8-a220-a93c1513c5d4
    clientSecret: _l:zI-_yrW75lV8M61K@z.I2K@B/On6Q
    redirectUri: https://zfile.jun6.net/onedirve/callback
    scope: offline_access User.Read Files.ReadWrite.All
  onedirve-china:
    clientId: 4a72d927-1907-488d-9eb2-1b465c53c1c5
    clientSecret: Y9CEA=82da5n-y_]KAWAgLH3?R9xf7Uw
    redirectUri: https://zfile.jun6.net/onedirve/china-callback
    scope: offline_access User.Read Files.ReadWrite.All

jetcache:
  statIntervalMinutes: 0
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson